# Develop A Business Model To Predict the Trend In Investment and Funding.

## Importing Libraries :

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

## Loading the Dataset

In [2]:
df=pd.read_csv("nse_stock.csv")

#### National Stock Exchange (NSE) Historical Inxdex Data for 10 Months from 1st January to October 2022

In [3]:
df

Open      High       Low     Close  Shares Traded  Turnover (Rs. Cr)  \
0    17681.40  17827.60  17593.55  17805.25      247437472           18604.16   
1    17820.10  17944.70  17748.85  17925.25      251460038           23737.31   
2    17768.50  17797.95  17655.55  17745.90      236454824           22643.82   
3    17797.60  17905.00  17704.55  17812.70      239338015           21447.89   
4    17913.30  18017.45  17879.15  18003.30      232418075           20853.64   
..        ...       ...       ...       ...            ...                ...   
180  17156.30  17196.40  16978.30  17016.30      492002942           27533.01   
181  17110.90  17176.45  16942.35  17007.40      359895458           22712.80   
182  16870.55  17037.60  16820.40  16858.60      323922457           21400.93   
183  16993.60  17026.05  16788.60  16818.10      340034380           24758.63   
184  16798.05  17187.10  16747.70  17094.35      380204763           26205.63   

       Return  
0    1.692342  
1    0.784440  
2   -0.289561  
3    0.163773  
4    0.650088  
..        ...  
180 -2.486949  
181 -0.264626  
182 -1.404660  
183  0.729378  
184 -1.150727  

[185 rows x 7 columns]

## Data Analysis :

### Analyzing the Dataset

In [4]:
df.head()

Open      High       Low     Close  Shares Traded  Turnover (Rs. Cr)  \
0  17681.4  17827.60  17593.55  17805.25      247437472           18604.16   
1  17820.1  17944.70  17748.85  17925.25      251460038           23737.31   
2  17768.5  17797.95  17655.55  17745.90      236454824           22643.82   
3  17797.6  17905.00  17704.55  17812.70      239338015           21447.89   
4  17913.3  18017.45  17879.15  18003.30      232418075           20853.64   

     Return  
0  1.692342  
1  0.784440  
2 -0.289561  
3  0.163773  
4  0.650088

In [5]:
df.tail()

Open      High       Low     Close  Shares Traded  Turnover (Rs. Cr)  \
180  17156.30  17196.40  16978.30  17016.30      492002942           27533.01   
181  17110.90  17176.45  16942.35  17007.40      359895458           22712.80   
182  16870.55  17037.60  16820.40  16858.60      323922457           21400.93   
183  16993.60  17026.05  16788.60  16818.10      340034380           24758.63   
184  16798.05  17187.10  16747.70  17094.35      380204763           26205.63   

       Return  
180 -2.486949  
181 -0.264626  
182 -1.404660  
183  0.729378  
184 -1.150727

In [6]:
df.describe()

Open          High           Low         Close  Shares Traded  \
count    185.000000    185.000000    185.000000    185.000000   1.850000e+02   
mean   16972.323784  17074.202703  16853.082973  16970.273514   2.949955e+08   
std      743.281043    731.122891    745.411085    741.577704   7.707790e+07   
min    15272.650000  15382.500000  15183.400000  15293.500000   1.830112e+08   
25%    16318.150000  16456.000000  16211.200000  16345.350000   2.455149e+08   
50%    17121.300000  17237.750000  17003.900000  17136.550000   2.766627e+08   
75%    17584.850000  17667.200000  17467.350000  17560.200000   3.216603e+08   
max    18337.200000  18350.950000  18228.750000  18308.100000   6.516136e+08   

       Turnover (Rs. Cr)      Return  
count         185.000000  185.000000  
mean        23399.181892   -0.010757  
std          5426.417559    1.256587  
min         16042.520000   -3.754689  
25%         19875.220000   -0.825562  
50%         22007.780000    0.085585  
75%         25419.500000    0.812996  
max         52929.350000    4.223784

In [7]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Shares Traded', 'Turnover (Rs. Cr)',
       'Return'],
      dtype='object')

In [8]:
df.isnull().sum()

Open                 0
High                 0
Low                  0
Close                0
Shares Traded        0
Turnover (Rs. Cr)    0
Return               0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Open               185 non-null    float64
 1   High               185 non-null    float64
 2   Low                185 non-null    float64
 3   Close              185 non-null    float64
 4   Shares Traded      185 non-null    int64  
 5   Turnover (Rs. Cr)  185 non-null    float64
 6   Return             185 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 10.2 KB


In [10]:
df.shape

(185, 7)

In [11]:
df.dtypes

Open                 float64
High                 float64
Low                  float64
Close                float64
Shares Traded          int64
Turnover (Rs. Cr)    float64
Return               float64
dtype: object

## Extracting Dependent And Independent Variable

In [12]:
x = df.iloc[:, 0:-1].values # Getting a Copy Of Dataset Excluding Last Column(Target Variable)
y = df.iloc[:, -1].values # Getting a Copy of Target Variable as an Array

In [13]:
x # Independent Variable

array([[1.76814000e+04, 1.78276000e+04, 1.75935500e+04, 1.78052500e+04,
        2.47437472e+08, 1.86041600e+04],
       [1.78201000e+04, 1.79447000e+04, 1.77488500e+04, 1.79252500e+04,
        2.51460038e+08, 2.37373100e+04],
       [1.77685000e+04, 1.77979500e+04, 1.76555500e+04, 1.77459000e+04,
        2.36454824e+08, 2.26438200e+04],
       ...,
       [1.68705500e+04, 1.70376000e+04, 1.68204000e+04, 1.68586000e+04,
        3.23922457e+08, 2.14009300e+04],
       [1.69936000e+04, 1.70260500e+04, 1.67886000e+04, 1.68181000e+04,
        3.40034380e+08, 2.47586300e+04],
       [1.67980500e+04, 1.71871000e+04, 1.67477000e+04, 1.70943500e+04,
        3.80204763e+08, 2.62056300e+04]])

In [14]:
y # Dependent Variable

array([ 1.69234176,  0.78444015, -0.28956066,  0.16377297,  0.65008765,
        0.47143742,  0.95928658,  0.4765993 , -0.39436928,  0.27852626,
        0.55687623, -1.13430622, -1.14842354, -1.71474806, -0.21886373,
       -3.26369903,  0.35555582,  0.85746102,  0.53898409,  1.32015109,
        1.00830317,  0.34761835, -0.99928241, -0.76121931, -1.01080985,
        0.52228463,  1.05929154, -0.58732718, -2.14801444, -0.83683969,
        2.80631302, -0.06835761, -0.92259672, -0.25411855, -2.00264654,
        2.05692681, -3.754689  , -0.2009197 , -0.20616809,  0.67651199,
        0.78406084, -2.29471632, -2.88565405, -0.75750176,  2.09712499,
        4.22378405, -1.36240758,  0.63464982,  1.60487444, -0.14200637,
        1.93314432,  0.73592243, -1.206613  ,  1.66263639, -1.78166681,
        1.13513055, -0.61975823,  0.67134796,  0.98831025,  0.29224617,
       -0.46977031,  2.13455373,  1.52450152, -1.31549838, -0.66945958,
       -0.1419036 ,  0.24155067, -0.87960588,  0.08558504, -2.36

## Splitting the Dataset Into Training And Test Set 

In [15]:
# Importing train_test_split function
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(129, 6)
(56, 6)
(129,)
(56,)


## Trends in NSE Stocks Dataset

## Linear Regression

In [18]:
# Importing LinearRegression function
from sklearn.linear_model import LinearRegression

In [19]:
lr=LinearRegression()

# Fitting Linear Regression to the Training Set

In [20]:
lr.fit(x_train,y_train)

LinearRegression()

# Regression Co-efficient

In [21]:
print(lr.coef_)

[ 2.14075607e-03 -3.68220221e-03  1.71676834e-03  4.29223987e-05
 -1.08331079e-09  2.22813509e-05]


# Intercept

In [22]:
print(lr.intercept_)

-3.3509852899767307


# Predicting the Test Set Result

In [23]:
y_pred=lr.predict(x_test)

In [24]:
y_pred

array([ 0.46629894,  0.42005698, -0.19221976, -0.38746993, -0.15316676,
       -0.02394932, -0.41744696,  0.40327809, -0.15312172, -0.27512883,
       -0.51269217, -0.11343403, -0.87070858, -0.03560251, -0.28524197,
       -0.07166233,  0.18816096, -0.16550389, -0.04859961, -0.19392806,
        0.09357535, -0.02871185,  0.35607098,  0.21673172, -0.3950549 ,
       -0.50352131,  0.22052719,  0.25711588, -0.16645063, -0.25582746,
        0.22890523, -0.04878644, -0.00202384,  0.0738453 , -0.2448665 ,
        0.17558158, -0.02832243, -0.17538821, -0.26796474,  0.09250231,
        0.34985286,  0.18115621,  0.11186685, -0.36390652, -0.22932736,
        0.33309614,  0.36934971,  0.21803657,  0.40737825, -0.94733652,
        0.06238823, -0.56669939,  0.11101807,  0.15814595,  0.17100151,
       -0.69354572])

# Evaluating The Model

In [25]:
# Importing mean_squared_error, r2_score function from sklearn.metrics module
from sklearn.metrics import mean_squared_error, r2_score

# Mean Squared Error (MSE)

In [29]:
mse = mean_squared_error(y_test, y_pred)
print('Mean_Squared_Error :' ,mse)

Mean_Squared_Error : 0.12245688856242


# R-squared (R2)

In [30]:
r_squared = r2_score(y_test, y_pred) 
print('r_square_value :',r_squared)

r_square_value : 0.923654855969756


# Error Rate

In [31]:
print('Error Rate : ',1-r_squared)

Error Rate : 0.0812638489886528
